version: '3'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: adminflask
      POSTGRES_PASSWORD: admin123
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data

  app:
    restart: always
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["python", "app.py"]
    env_file:
      - .env
    ports:
      - 5000:5000


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080







