version: '3'

services:
  app:
    restart: always
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: [ "python", "app.py", "run" ]
    env_file:
      - .env
    ports:
      - 5555:5000
  db:
    image: postgres:10
    restart: always
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: flask
      POSTGRES_USER: adminflask
      POSTGRES_PASSWORD: admin123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  postgres_data:





